#!/usr/bin/env python3
"""Generate a Markdown inventory of canonical agent-facing assets (.cursor/ SoT)."""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import NamedTuple

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "reference" / "agent-asset-inventory.md"
_FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n?(.*)\Z", re.DOTALL)
_KEY_RE = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$")
_HEADER_RE = re.compile(r"^#\s+(.+)$", re.MULTILINE)


class Asset(NamedTuple):
    name: str
    kind: str
    path: Path
    description: str


def _relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _display_path(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _parse_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    metadata: dict[str, str] = {}
    for line in match.group(1).splitlines():
        key_match = _KEY_RE.match(line)
        if key_match:
            metadata[key_match.group(1)] = key_match.group(2).strip().strip("\"'")
    return metadata, match.group(2)


def _clean_cell(text: str) -> str:
    return " ".join(text.replace("|", "\\|").split())


def _first_heading_or_sentence(path: Path, body: str) -> str:
    heading = _HEADER_RE.search(body)
    if heading:
        return _clean_cell(heading.group(1).strip())
    for line in body.splitlines():
        stripped = line.strip().lstrip("#").strip()
        if stripped:
            return _clean_cell(stripped.rstrip("."))
    return path.stem


def _command_assets(root: Path) -> list[Asset]:
    command_root = root / ".cursor" / "commands"
    assets: list[Asset] = []
    if not command_root.is_dir():
        return assets
    for path in sorted(command_root.glob("*.md")):
        _metadata, body = _parse_frontmatter(path)
        assets.append(
            Asset(
                name=f"/{path.stem}",
                kind="Slash command",
                path=path,
                description=_first_heading_or_sentence(path, body),
            )
        )
    return assets


def _skill_assets(root: Path) -> list[Asset]:
    skill_root = root / ".cursor" / "skills"
    assets: list[Asset] = []
    if not skill_root.is_dir():
        return assets
    for path in sorted(skill_root.glob("*/SKILL.md")):
        metadata, body = _parse_frontmatter(path)
        assets.append(
            Asset(
                name=metadata.get("name", path.parent.name),
                kind="Skill",
                path=path,
                description=_clean_cell(
                    metadata.get("description") or _first_heading_or_sentence(path, body)
                ),
            )
        )
    return assets


def _rule_assets(root: Path) -> list[Asset]:
    rule_root = root / ".cursor" / "rules"
    assets: list[Asset] = []
    if not rule_root.is_dir():
        return assets
    for path in sorted(rule_root.glob("*.mdc")):
        metadata, body = _parse_frontmatter(path)
        assets.append(
            Asset(
                name=path.stem,
                kind="Rule",
                path=path,
                description=_clean_cell(
                    metadata.get("description") or _first_heading_or_sentence(path, body)
                ),
            )
        )
    return assets


def collect_assets(root: Path = ROOT) -> list[Asset]:
    """Return the canonical Cursor command, skill, and rule inventory."""
    return [*_command_assets(root), *_skill_assets(root), *_rule_assets(root)]


def render_inventory(root: Path = ROOT) -> str:
    assets = collect_assets(root)
    stamp = "2026-07-26T00:00:00Z"
    sections = [
        "---",
        "type: Technical Reference",
        "title: Agent Asset Inventory",
        "description: Generated index of canonical Cursor commands, skills, and rules.",
        "resource: reference/agent-asset-inventory.md",
        "tags: [agents, inventory, generated]",
        f"timestamp: {stamp}",
        "okf_version: 0.1",
        "---",
        "",
        "# Agent Asset Inventory",
        "",
        "_Generated by `scripts/generate_agent_asset_inventory.py`; do not edit by hand._",
        "",
        "Canonical tree: **`.cursor/`**. Mirrored to `.claude/` by `scripts/sync_assistant_trees.py`.",
        "",
    ]
    for kind in ("Slash command", "Skill", "Rule"):
        matching = [asset for asset in assets if asset.kind == kind]
        sections.extend(
            [
                f"## {kind}s",
                "",
                "| Name | Canonical path | Description |",
                "|------|----------------|-------------|",
            ]
        )
        for asset in matching:
            sections.append(
                f"| `{asset.name}` | `{_relative(asset.path, root)}` | {asset.description} |"
            )
        sections.append("")
    return "\n".join(sections).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate docs/reference/agent-asset-inventory.md from .cursor/"
    )
    parser.add_argument("--check", action="store_true", help="Fail if the inventory is stale")
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT, help="Inventory file to write or check"
    )
    args = parser.parse_args(argv)

    expected = render_inventory(ROOT)
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        output_label = _display_path(args.output, ROOT)
        if actual != expected:
            print(f"OUT OF SYNC: {output_label}")
            print(
                f"Run `python {Path(__file__).relative_to(ROOT).as_posix()}` to regenerate it."
            )
            return 1
        print(f"in sync: {output_label}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"wrote {_display_path(args.output, ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
