"""Write Ultralytics image lists mixing CUB boxes with the teacher pseudo-labels.

    python -m training.teacher.make_mixed_det_lists --root /data --out data/bird_det_teacher_v1 --repeat 5

CUB (`wildlife_bird_det`) has ~20k training images and the teacher set ~800, so the teacher images are
listed `--repeat` times to give its small-bird, wildlife-context and bird-free frames real weight.
`--root` is the directory that holds both datasets as seen by the trainer (paths are written
absolute, so the lists work inside a container). Labels are found by Ultralytics' images/ -> labels/ rule.
"""
from __future__ import annotations

import argparse
from pathlib import Path

SETS = {"cub": "wildlife_bird_det", "teacher": "pseudo_rtmdet_v0"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True, help="dir containing wildlife_bird_det/ and pseudo_rtmdet_v0/")
    ap.add_argument("--local-root", default="data", help="same dir on this machine, for listing files")
    ap.add_argument("--out", required=True)
    ap.add_argument("--repeat", type=int, default=5)
    a = ap.parse_args()
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    counts = {}
    for split in ("train", "val"):
        lines = []
        for key, name in SETS.items():
            files = sorted(p.name for p in (Path(a.local_root) / name / "images" / split).glob("*.jpg"))
            reps = a.repeat if (key == "teacher" and split == "train") else 1
            lines += [f"{a.root.rstrip('/')}/{name}/images/{split}/{f}" for f in files] * reps
            counts[f"{key}_{split}"] = len(files) * reps
        (out / f"{split}.txt").write_text("\n".join(lines) + "\n")
    (out / "data.yaml").write_text(
        f"# Generated by training/teacher/make_mixed_det_lists.py: {counts}\n"
        f"train: {a.root.rstrip('/')}/{out.name}/train.txt\nval: {a.root.rstrip('/')}/{out.name}/val.txt\n"
        "names:\n  0: bird\n")
    print(counts)


if __name__ == "__main__":
    main()
